version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=andreea
      - POSTGRES_DB=lost-animals
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  backend:
    image: lost-animals-app-backend
    restart: always
    environment:
      DB_IP: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: andreea
      DB_DBNAME: lost-animals
    ports:
      - "8080:8080"
    depends_on:
      - postgres