spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lost-animals
    username: postgres
    password: andreea
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secretKey: 7A24432646294A404E635266556A586E5A7234753778214125442A472D4B6150